### PR TITLE
Issue#182 Fixed Left Toolbar Bug and Randomization (Would not update PR Issue #147 for some reason)

### PR DESCRIPTION
**Pull request by elizabethli1998**

### CODE REVIEW

**Comment by elizabethli1998** [comment]
Also fixes randomization aka Issue#147

**Comment by tomtinkerer** [comment]
Merge conflicts

**Comment by tomtinkerer** [comment]
Again :/

**Comment by tomtinkerer** [comment]
Sorry :/ LAST TIME!

**Comment by elizabethli1998** [comment]
For some reason, PEWI keeps breaking. Will try to fix this.

**Pull request closed without merging**
