### PR TITLE
Issue362

### PR DESCRIPTION
**Pull request by NicolasDelacruz**
In Issue362 the following were implemented: there was an "X" button added in the top right corner to exit and undo any selected options to the previous state. For more information refer to #362.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Just tested it. X button works, but does not revert to the previous setting.

Step 1: open instructor options
image

Step 2: click a few land uses
image

Step 3: Hit the X (should not save my current changes)
image

Step 4: Open instructor options again - changes should not have been saved, but they are.
image

**Comment by tomtinkerer** [comment]
Let me know when the code is done and ready for testing

**Comment by NicolasDelacruz** [comment]
The changes should be made. It was through commit 74088d4. Let me know if you cannot see it.

**Comment by tomtinkerer** [comment]
Resolves #362 

There are merge conflicts - please fix and I'll will merge!

**Pull request closed without merging**
