### PR TITLE
Issue460

### PR DESCRIPTION
**Pull request by saveripal**
#460

### CODE REVIEW

**Comment by saveripal** [comment]
Hi Robert,
It seems the pulls merge conflict is too complex to resolve on Github, that's why the button is deactivated. There are ways to do it. I'm looking in.

**Comment by saveripal** [comment]
Merge conflicts resolved.

**Comment by tomtinkerer** [comment]
Please retest - screenshot below shows how its displaying on my screen. I did clear FireFox cache before testing

image

**Comment by saveripal** [comment]
Sure.

**Comment by saveripal** [comment]
I tried running pewi on my home desktop before updating the branch to remote. It contained all the cursor tracking details and worked fine. However, once I updated the local branch to the remote, I too see this screen.  It seems some new update to development is causing a conflict that leads to this screen. I will figure it out.

**Comment by saveripal** [comment]
Fixed the bug. It was a merge conflict. PEWI loading fine correctly now. Let me know if you encounter any new issue.

**Comment by tomtinkerer** [comment]
More conflicts :/ resolve and I'll review!

**Comment by saveripal** [comment]
Done!

**Pull request merged**
