### PR TITLE
Issue476

### PR DESCRIPTION
**Pull request by paullicata**
Issue476  Autofill in min/max table occurs now when cell is clicked off 

#476

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Merge conflicts please resolve

**Comment by paullicata** [comment]
Merge conflicts resolved.

**Comment by tomtinkerer** [comment]
Found a bug.
- Set GW min to 10. 
- Set GW max to 110. It gets autocorrected to 100, but the raw score does not calculate.

**Comment by paullicata** [comment]
Fixed bug

**Pull request merged**
