### PR TITLE
[Issue285] Fixed print function.

### PR DESCRIPTION
**Pull request by qaws01395**
#285

### CODE REVIEW

**Comment by tomtinkerer** [comment]
merge conflict

**Comment by tomtinkerer** [comment]
Tested, getting an "unresponsive script" message

image

**Comment by qaws01395** [comment]
The library itself would have this problem. If one wants to print too many tables at once this will happen. I think I told you this before. But solving this needs to edit the library code or to look at other stuff inside. For now, I just change the script execution time longer in setting.

**Comment by tomtinkerer** [comment]
Thanks for clarification! I do remember that, but was unsure whether this was that error message or a new bug.

**Comment by tomtinkerer** [comment]
Resolves #285

**Pull request merged**
