### PR TITLE
Issue576

### PR DESCRIPTION
**Pull request by saveripal**
#576

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Conflicts!

**Comment by saveripal** [comment]
Merge conflicts resolved.

**Comment by tomtinkerer** [comment]
Core save function works great! However, I get the following error when loading a save file from PEWI v3.0, the current live version on the website. Please review for compatibility 

image

**Comment by saveripal** [comment]
can you send me the save file you were trying to upload?

**Comment by saveripal** [comment]
Resolved the compatibility issue with pewi-v3. Looking into the other bug.

**Comment by saveripal** [comment]
Don't check it yet. I found another bug after updating with latest development.

**Comment by saveripal** [comment]
Ready to be tested!

**Comment by nbatwara** [comment]
@tomtinkerer did you by any chance look at this again?

**Pull request merged**
