### PR TITLE
Ability to remove objectives added

### PR DESCRIPTION
**Pull request by Xemnaes**
The function deleteObjective was added in levelDesigner.js to allow users to remove previously created objectives. A button has been added to levelDesigner.html to toggle this action.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Please review, contains conflicts with the first PR I accepted from you

**Comment by Xemnaes** [comment]
Conflicts resolved.

**Comment by tomtinkerer** [comment]
Here we go again

**Comment by tomtinkerer** [comment]
Well done!

**Comment by tomtinkerer** [comment]
Resolves #104

**Pull request merged**
