### PR TITLE
Issue700; Select/Deselect added;

### PR DESCRIPTION
**Pull request by nbatwara**
#700

### CODE REVIEW

**Comment by nbatwara** [comment]
Please test again. This took very long because each graphic has 3 different ways to do selections.

**Comment by tomtinkerer** [comment]
@nbatwara  First off, good job on this. Graphic 1 is good to go. Still some bugs on the other ones though.

Graphic 2 - "Land Uses" and "Cost Categories" has a minor bug. You have to click twice to change from "no check" to "check"

Graphic 3 - Deselecting land uses is not properly updating the graphic's bars. Also, test with 2 or 3 years. You'll see data is only appearing in year 1, with the others being blank. 

Graphic 5 - "Select/Deselect All" is still inverting what's selected. the other check boxes are not updating accordingly. Problem confirmed for both "Bar Selection" and "Line Selection"

**Comment by nbatwara** [comment]
G2 - there is a phantom click happening so one extra click is needed (there is some difference in handling these checkboxes and I couldn't find that) 

G3 - multiple years worked correctly for me; might have to test with you. Deselecting also worked for me and I didn't change anything on this yet. 

G5 - this should be fixed now.

**Comment by tomtinkerer** [comment]
@nbatwara Good work. 
G2 - We'll accept this as is for now. At some point in the future what needs to happen is a rework of all 5 graphics to follow similar architecture, but we don't have the time at the moment.

G3 - Years are working fine for me now. However, Land Uses are not. Do the following: create a scenario with 2 years, with different watershed designs. Then go to G3, deselect a few land uses, then click "Select/Deselect All". You'll see what I'm talking about.

G5 - Done, works great!

**Comment by nbatwara** [comment]
@tomtinkerer please test graphic 3 again.

**Comment by tomtinkerer** [comment]
Works now! Great job!

**Pull request merged**
