### PR TITLE
Issue182

### PR DESCRIPTION
**Pull request by elizabethli1998**
One more attempt to add the randomization feature and fix the Left Toolbar.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Please test to verify it works. I am still seeing same functionality as when we lasted discussed it

**Comment by elizabethli1998** [comment]
Update: The "Save and Exit" bug is fixed. However, the default landuse feature still needs to be implemented.

**Comment by elizabethli1998** [comment]
This and the Issue with the Left Toolbar Bug should be good to go now!

**Comment by tomtinkerer** [comment]
Resolves #147

**Pull request merged**
