### PR TITLE
Issue93 print function

### PR DESCRIPTION
**Pull request by qaws01395**
#93

### CODE REVIEW

**Comment by qaws01395** [comment]
don't push yet. trying to get rid of those repeat commits.

**Comment by tomtinkerer** [comment]
Merge conflicts: should be small

**Comment by qaws01395** [comment]
Since this on is huge I will fix the conflicts until any other pull requests are pushed.

**Comment by tomtinkerer** [comment]
Ready to go!

**Comment by tomtinkerer** [comment]
Merged! Resolves #93

**Pull request merged**
