### PR TITLE
Issue124 - Aggregating multiplayer maps update

### PR DESCRIPTION
**Pull request by qaws01395**
This time pull request to development branch.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Please test. This code broke the "Results" button and the ESC key (might be related or intertwined) in the Sandbox area. For some reason, it did not break these features in "Play" lessons area.

Also, in multiplayer division, the flyover bird is immediately triggered. Made me smile, but still.... need to fix :)

**Comment by qaws01395** [comment]
I did not see the reported errors and I'm not sure what happened. But there are some weird bugs sometimes happen sometimes not. Not frequently so I still can't figure out the reason. And I found this pull request makes save/upload popup didn't work correctly though.

**Comment by qaws01395** [comment]
I think it works now.

**Comment by qaws01395** [comment]
OK, it works! With one problem.....

Let's say File 1 is in Folder A, and File 2 is in Folder B. Right now, there is no way to add both. (First add File 1, then add File 2. File 2 will remove File 1 from the list.)

**Comment by tomtinkerer** [comment]
Resolves #124

**Pull request merged**
