### PR TITLE
Issue#97

### PR DESCRIPTION
**Pull request by elizabethli1998**

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Conflicts have appeared, please resolve

**Comment by elizabethli1998** [comment]
Conflicts resolved

**Comment by tomtinkerer** [comment]
Please retest. Something broke 
image

**Comment by elizabethli1998** [comment]
Updated so the code doesn't break- it appears to work when I tested it so hopefully this will work now!

**Comment by tomtinkerer** [comment]
Well done!

**Comment by tomtinkerer** [comment]
Resolves #97

**Pull request merged**
