### PR TITLE
Issue562

### PR DESCRIPTION
**Pull request by saveripal**
#562

### CODE REVIEW

**Comment by tomtinkerer** [comment]
@saveripal Looking it over looks good. Question though - why did you gt rid of the "https" for "http"? We've had a bug in the past related to this, that's why we use https whenever possible. Please test with https and let me know the results - if it works, please change back to https

**Comment by saveripal** [comment]
Weirdly enough it shows that I made those changes. I have no idea why. I
did not fiddle with the http and https.
Should I just change them back to https?

**Comment by saveripal** [comment]
I will test it with https then.

**Comment by saveripal** [comment]
Hi Robert,
All those lines of code with http instead of https are commented out. So it is not affecting the code in any way.  I think we are good to go with this one.

**Comment by saveripal** [comment]
Do let me know if you find any other issues though.

**Pull request merged**
