### PR TITLE
Issue734: Update Corn/Soybean Yield values in Results Table. 

### PR DESCRIPTION
**Pull request by nbatwara**
#734

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Seems to be working on the results pages and econ graphics/table. However, not working on the progress bars.

**Comment by tomtinkerer** [comment]
@nbatwara Were my last comments on this issue ever addressed?

**Comment by nbatwara** [comment]
Just saw this; This should work on Progress Bars now. Let me know if I missed anything.

**Comment by tomtinkerer** [comment]
@nbatwara This one is still throwing bugs for me. Requesting we schedule a time to meet via Zoom and knock it out ASAP - let me know when works for you

**Pull request merged**
