### PR TITLE
Issue103 - Save/Download Prompt when Exiting

### PR DESCRIPTION
**Pull request by qaws01395**
Check if you like it :+1:   #103

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Some conflicts have arisen do to recent merges

**Comment by tomtinkerer** [comment]
Conflicts fixed, but now this is what I'm getting:
image

**Comment by qaws01395** [comment]
I deleted wrong code when I merged it. Try it again.

**Comment by tomtinkerer** [comment]
A couple change requests:
- Prompt should only appear when leaving Sandbox, a loaded Play level, or Multiplayer Divisions. Should not appear when leaving from the Main Menu
- Open PEWI, attempt to leave/closeout the program. Prompt goes off. Hit cancel, then open Sandbox. The Download/Upload window is pulled up by default. (Shouldn't be)

**Comment by qaws01395** [comment]
I added the requests. Please try again.

**Comment by tomtinkerer** [comment]
New changes have undone intended prompted in main Sandbox area. We should talk about this tomorrow

**Comment by qaws01395** [comment]
Hopefully it works this time.

**Comment by tomtinkerer** [comment]
FANTASTIC! Fixed everything.

ONE LAST BUG/thing to change: Open PEWI>Utilities>Setup Multiplayer
Add at least a second player with some land.
Hitting "v" on the keyboard (download prompt)
Select "download multiplayer maps", save the files
Click Return to Start
The save prompt pops up. It should NOT pop up here.

This is the LAST change!

**Comment by tomtinkerer** [comment]
Resolves #103

**Pull request merged**
