### PR TITLE
Issue555

### PR DESCRIPTION
**Pull request by paullicata**
Interactive table

### CODE REVIEW

**Comment by paullicata** [comment]
Issue should be completed now.

**Comment by tomtinkerer** [comment]
#555

**Comment by tomtinkerer** [comment]
Still testing this, but could you please make two quick changes:
(1) Remove/hide the button for "View Enterprise Budgets"
(2) Add some blank space at the bottom. Not a lot, but enough for the hover effects on your graphic at the bottom not be hidden.

**Comment by tomtinkerer** [comment]
(3) Treat all values as dollars. That is:
(A) Right aligned
(B) Two decimal value, always (values, totals, and graphic)
(C) Use commas within numbers as appropriate

**Comment by tomtinkerer** [comment]
(4) How hard would it be to add sorting to the Value column?

**Pull request merged**
