### PR TITLE
Issue#166c

### PR DESCRIPTION
**Pull request by mehulshinde**

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Merge conflicts have arisen

**Comment by tomtinkerer** [comment]
Tested your version, functionality is EXACTLY what we were looking for! Resolve the conflict, and I'll push the PR!

**Comment by tomtinkerer** [comment]
Don't forget about this PR

**Comment by mehulshinde** [comment]
Waiting for other PR's to go through before fixing the merge conflicts

**Comment by tomtinkerer** [comment]
FYI still here :)

**Comment by mehulshinde** [comment]
Yes, there was a major bug in development which broke my issue fix. Will push the changes today.

**Comment by mehulshinde** [comment]
Closing this one because the most recent version is in #212

**Pull request closed without merging**
