### PR TITLE
Issue386

### PR DESCRIPTION
**Pull request by NicolasDelacruz**
In  Issue 386 the results page was modified for the multiplayer mode. These changes only apply to the multiplayer mode. For more details of the changes made to the results page and the issue refer to #386 .

### CODE REVIEW

**Comment by tomtinkerer** [comment]
This works perfectly! Only one change request: have the results table only display data for active players (if land owned = 0, then do no display rows for them).

**Comment by NicolasDelacruz** [comment]
The change was added. I took the freedom to also apply a similar change to the strategic wetland use (SWU) table. The change goes as follows: before the SWU table would show all 6 players, but now the SWU table only reflects the same players that are in the parcel size table (table 1). If this change does not look good or would like a different change here or anywhere in this issue then let me know and I will make the changes accordingly.

**Comment by NicolasDelacruz** [comment]
Color change on pie graph has been changed. If this change does not look good or would like a different change here or anywhere in this issue then let me know and I will make the changes accordingly.

**Comment by tomtinkerer** [comment]
Resolves #386

**Pull request merged**
