### PR TITLE
Issue#180 Logo Placement

### PR DESCRIPTION
**Pull request by elizabethli1998**

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Merge conflicts

**Comment by elizabethli1998** [comment]
Merge conflicts fixed- it should be good to go now!

**Comment by tomtinkerer** [comment]
Again :/

**Comment by elizabethli1998** [comment]
Hopefully it should work now

**Comment by tomtinkerer** [comment]
Something's up on the Sandbox page

image

**Comment by elizabethli1998** [comment]
Hopefully should be good to go now.

**Comment by tomtinkerer** [comment]
Looks good now, but there is a bug. Open PEWI, Main Menu page shows logo. Enter Sandbox, then exit and return to Main Menu. Now PEWI logo is vanished....where'd it go?

**Comment by elizabethli1998** [comment]
The Logo shouldn't be vanishing now, thanks to the most recent commit. (Did not notice this bug earlier as I never went back to the main menu to check, forgetting that you could do that.)

**Comment by tomtinkerer** [comment]
Resolves #180

**Pull request merged**
