### PR TITLE
Issue506

### PR DESCRIPTION
**Pull request by saveripal**
#506
I have been able to re-align Undo with cell paint and grid paint. However, adding a hover effect dips the Undo button by a very thin line. So I have removed the effect as of now. The classes "tooltip" and "tooltiptext" seems to be causing the dipping. I need to look into the classes to determine why there is this dipping effect. One thing I have noticed is that "tooltip" is defined separately for each tab and their child categories.
The other hover effects for cell paint, grid paint, home, print, email, credits work fine.
I am opening this pull request so you can check it. 
Check the latest commit not any thing before that. I kind of messed up the previous commits and pushes.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
@saveripal Confirming, is this ready for me to test?

**Comment by saveripal** [comment]
No, it is not complete yet.

**Comment by saveripal** [comment]
Wait, you can test it. I already know one thing that is wrong with it. But
if you see anything else, I could work on them too.
So go ahead and test and let me know.

**Comment by saveripal** [comment]
#506 
Hover effect for Undo button added and placed correctly. The other upper buttons have hover effects too. Check and let me know !

**Comment by tomtinkerer** [comment]
Looks good!

One more thing: please add titles to Upload/Download buttons. Then this will be good to merge

**Comment by saveripal** [comment]
Hover for upload, download added.

**Pull request merged**
