### PR TITLE
Combined PR for 753, 754, 755, 756, 757, 760, 761

### PR DESCRIPTION
**Pull request by nbatwara**
#754, #755

### CODE REVIEW

**Comment by tomtinkerer** [comment]
@nbatwara #754 and #755 are good to go! However, #753 (bubble graphic updates) are not showing on my end. 

image

**Comment by nbatwara** [comment]
competed #760, #761. Removed #753 because I found a bug in my implementation.

**Comment by tomtinkerer** [comment]
Progress bars look great! 

Results Table, for "Stream Biodiversity" and "Aquatic Health" the English and Metric columns should have values of 5 (instead of 50), and change the units to "pts" (same as Land Biodiversity and Game Wildlife).
image

**Comment by nbatwara** [comment]
Added #753

**Comment by tomtinkerer** [comment]
Hey Neh, good job on the bubble graphic. Still some things though, see below:

Change the "tons / yr" for Aquatic Health to "pts / yr". Get rid of "Mg / yr". (This metric is like Game Wildlife and Land/Stream Biodiversity scores, just a point system.)
image

Updates to the Spider diagram were somehow. Please restore.
image

Otherwise looks great!

**Comment by nbatwara** [comment]
@tomtinkerer hey Robert, #757 has a comment saying you handled the updates to the spider diagram which is why I got confused and didn't add them. Are you going to be pushing those with your 756 changes?

**Comment by tomtinkerer** [comment]
@nbatwara Apologies that's old intel, I thought we'd discussed that you'd do it (and it was in your last branch iteration, I believe?). Could you please add it back to this branch/PR

**Comment by nbatwara** [comment]
Oh some how I got confused and thought we were talking about me doing the bubble graphic instead of you (#753), sorry about that! I'll go ahead and work on it.

**Comment by tomtinkerer** [comment]
@nbatwara Thanks! Should be a very quick implementation, the code on that one isn't bad

**Comment by nbatwara** [comment]
@tomtinkerer done - you can test now.

**Pull request merged**
