### PR TITLE
Issue532

### PR DESCRIPTION
**Pull request by jbweiland**
Added all of the CCs that I could find in the code.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
We need to talk this one over, it's causing some chopping jumping with the camera after angle adjustments

**Comment by jbweiland** [comment]
Interesting, all I did was add text in the credits.html file.

**Comment by jbweiland** [comment]
Nvmd, its because the checkZValue function somehow made it in there from the issue I was working on dealing with the map disappearing. I will fix that right now.

**Comment by tomtinkerer** [comment]
#532

**Pull request merged**
