### PR TITLE
Issue482

### PR DESCRIPTION
**Pull request by saveripal**
#482 
Added the controls on screen. 
Personally I feel,
1. The control buttons look small on the pewi screen and needs to be enlarged.
2. The fonts on the buttons are not 'Amatic SC' as all the fonts in pewi. It is because I could not import it into the library computer I was using due to administrator permission issue. 

Check it out and let me know how you want it modified.

### CODE REVIEW

**Comment by saveripal** [comment]
Added the new version of navigation images to PEWI. Kindly check and let me know.

**Comment by saveripal** [comment]
smaller font size changed to 11 from 8.

**Comment by tomtinkerer** [comment]
Looks great! Found a bug though - the images need to display only when in FlyOver mode. Right now, they're triggering on any use of hotkeys.

**Comment by tomtinkerer** [comment]
Merge Conflicts, please resolve

**Comment by saveripal** [comment]
merger conflicts resolved.

**Pull request merged**
