### PR TITLE
Issue156 pull request

### PR DESCRIPTION
**Pull request by qaws01395**
closing up #156 

First commit
1. Update 3 libraries: JQuery,jszip, three.js.
2. Fix css bugs appear to IE, Edge
3. Highlight some text in background info box
4. Format some code and make them concise or more efficient
5. Fix upper right logo positions problem
6. Fix resizing bug for right hand side info box and popup message
7. Change some unit px to vw in order to resize with screen

Second
1. Try to make key event compatible with IE/Edge, but not seems working
so comment out for now.
2. Do some code formatting and clean up some unecessary code.
3. Fix result page IE compatibility problem.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Resolves #156

**Comment by tomtinkerer** [comment]
@qaws01395 Does this resolves any other issues as well?

**Comment by qaws01395** [comment]
What do you mean by any other issue?

**Comment by tomtinkerer** [comment]
For example, does this include any changes for Chrome compatibility (Issue157)?

**Comment by qaws01395** [comment]
I don't think so. I did not look into detail for Chrome, but when I opened Chrome there are no big problems relating to it.

**Pull request merged**
