### PR TITLE
Issue460

### PR DESCRIPTION
**Pull request by saveripal**
#460 
This issue is done except hover effect of ecosystem radar chart in results iframe.

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Merge Conflicts, please resolve

**Comment by tomtinkerer** [comment]
Merge conflicts

**Comment by saveripal** [comment]
On my to-do.

**Comment by saveripal** [comment]
Hi Robert, 
I am not able to click on the 'Resolve Conflicts' button. I was able to the first time. After that it doesn't allow me. Any idea why that might happen?

**Pull request closed without merging**
