### PR TITLE
Issue595

### PR DESCRIPTION
**Pull request by HameisterEric**
#595

### CODE REVIEW

**Comment by tomtinkerer** [comment]
Eric you need to test this.....this code replaces the entire map, regardless of previous land us

**Comment by HameisterEric** [comment]
Problem has been fixed.

**Comment by tomtinkerer** [comment]
Seems to work now. However, the replacement is not cascading into Results Graphic 1

**Comment by HameisterEric** [comment]
I can't reopen, but this commit now has a parent being a stable version of development.

**Pull request merged**
